### ISSUE TITLE
Problem in loading onnx model with a lstm layer

### ISSUE THREAD

**Issue by thistlillo** [deephealthproject/pyeddl#72] opened 2022-02-11 14:04 UTC
I am not able to read a model containing a LSTM layer from an onnx file, saved after training the model.

Settings:
```
Python 3.8.6 | packaged by conda-forge | (default, Oct  7 2020, 19:08:05) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyeddl 
>>> import pyecvl
>>> print(pyeddl.__version__)
1.2.0
>>> print(pyecvl.__version__)
1.0.0
```
You can run the code below to try and replicate the issue:
```python
import pyeddl.eddl as eddl
from pyeddl.tensor import Tensor
import numpy as np


bs = 20
visual_dim = 3
semantic_dim = 3
vs = 3
emb_size = 200
n_tokens = 3

visual_x = Tensor.fromarray(np.random.randn( bs, visual_dim ))
semantic_x = Tensor.fromarray(np.random.randn( bs, semantic_dim ))

text = Tensor.fromarray(np.random.randint(0, vs+1, size=(bs, n_tokens, vs)))
text = Tensor.onehot(text, vs)

print(type(visual_x))
print(type(semantic_x))
print(type(text))

#print(visual_x.getdata())
#print(semantic_x.getdata())
#print(text.getdata())

# INPUT: visual features
cnn_top_in = eddl.Input([visual_dim], name="in_visual_features")
visual_features = eddl.RandomUniform(eddl.Dense(cnn_top_in, cnn_top_in.output.shape[1], name="visual_features") )
alpha_v = eddl.Softmax(eddl.Dense(eddl.Tanh(visual_features), visual_features.output.shape[1]), name="alpha_v")  # missing sentence component
v_att = eddl.Mult(alpha_v, visual_features)
print(f"layer visual features: {visual_features.output.shape}")

# INPUT: semantic features
cnn_out_in = eddl.Input([semantic_dim], name="in_semantic_features")
semantic_features = eddl.RandomUniform(eddl.Embedding(eddl.ReduceArgMax(cnn_out_in, [0]), cnn_out_in.output.shape[1], 1, emb_size, name="semantic_features"), -0.05, 0.05)
alpha_s = eddl.Softmax(eddl.Dense(eddl.Tanh(semantic_features), emb_size), name="alpha_s")  # missing sentence component cnn_out.output.shape[1]
s_att = eddl.Mult(alpha_s, semantic_features)
print(f"layer semantic features: {semantic_features.output.shape}")

# co-attention (not exactly, just a reference to the full model)
features = eddl.Concat([v_att, s_att], name="co_att_in")
context = eddl.Dense(features, emb_size, name="co_attention")
print(f"layer coattention: {context.output.shape}")

# lstm
word_in = eddl.Input([vs])
to_lstm = eddl.ReduceArgMax(word_in, [0])
to_lstm = eddl.RandomUniform(eddl.Embedding(to_lstm, vs, 1, emb_size, mask_zeros=True, name="word_embeddings"), -0.05, +0.05)
to_lstm = eddl.Concat([to_lstm, context])
lstm = eddl.LSTM(to_lstm, emb_size, mask_zeros=True, bidirectional=False, name="lstm")
eddl.setDecoder(word_in)

out_lstm = eddl.Softmax(eddl.Dense(lstm, vs, name="top_dense"), name="rnn_out")
print(f"layer lstm: {out_lstm.output.shape}")

# model
rnn = eddl.Model([cnn_top_in, cnn_out_in], [out_lstm])
eddl.build(rnn, eddl.adam(0.001), ["softmax_cross_entropy"], ["accuracy"], eddl.CS_GPU(g=[1], mem="full_mem"))
eddl.summary(rnn)

eddl.fit(rnn, [visual_x, semantic_x], [text], bs, 1)

eddl.save_net_to_onnx_file(rnn, "rnn.onnx")
# XXX
rnn = eddl.import_net_from_onnx_file("rnn.onnx")
``` 
The output is:
```
<class 'pyeddl._core.Tensor'>
<class 'pyeddl._core.Tensor'>
<class 'pyeddl._core.Tensor'>
layer visual features: [1, 3]
layer semantic features: [1, 200]
layer coattention: [1, 200]
layer lstm: [1, 3]
Generating Random Table
CS with full memory setup
Building model
Selecting GPU device 0
EDDL is running on GPU device 0, Tesla T4
CuBlas initialized on GPU device 0, Tesla T4
CuRand initialized on GPU device 0, Tesla T4
CuDNN initialized on GPU device 0, Tesla T4
-------------------------------------------------------------------------------
model
-------------------------------------------------------------------------------
in_visual_features  |  (3)                 =>   (3)                 0         
visual_features     |  (3)                 =>   (3)                 12        
tanh1               |  (3)                 =>   (3)                 0         
dense1              |  (3)                 =>   (3)                 12        
alpha_v             |  (3)                 =>   (3)                 0         
mult_1              |  (3)                 =>   (3)                 0         
in_semantic_features|  (3)                 =>   (3)                 0         
reduction_argmax1   |  (3)                 =>   (1)                 0         
semantic_features   |  (1)                 =>   (200)               600       
tanh2               |  (200)               =>   (200)               0         
dense2              |  (200)               =>   (200)               40200     
alpha_s             |  (200)               =>   (200)               0         
mult_2              |  (200)               =>   (200)               0         
co_att_in           |  (3)                 =>   (203)               0         
co_attention        |  (203)               =>   (200)               40800     
input1              |  (3)                 =>   (3)                 0         
reduction_argmax2   |  (3)                 =>   (1)                 0         
word_embeddings     |  (1)                 =>   (200)               600       
concat1             |  (200)               =>   (400)               0         
lstm                |  (400)               =>   (200)               480800    
top_dense           |  (200)               =>   (3)                 603       
rnn_out             |  (3)                 =>   (3)                 0         
-------------------------------------------------------------------------------
Total params: 563627
Trainable params: 563627
Non-trainable params: 0

Vec2Seq 1 to 3
Recurrent net output sequence length=3
CS with full memory setup
Building model without initialization
Unroll on device
Recurrent net output sequence length=3
1 epochs of 1 batches of size 20
Epoch 1
[██████████████████████████████████████████████████] 1 rnn_out[loss=1.069 metric=0.600] 0.0636 secs/batch
0.0636 secs/epoch
[ONNX::Export] Warning: The LSTM layer lstm has mask_zeros=true. This attribute is not supported in ONNX, so the model exported will not have this attribute.
==================================================================
⚠️  LDense only works over 2D tensors (LDense) ⚠️
==================================================================

Traceback (most recent call last):
  File "2022_lstm.py", line 66, in <module>
    rnn = eddl.import_net_from_onnx_file("rnn.onnx")
  File "/root/miniconda3/envs/pyeddl-cudnn/lib/python3.8/site-packages/pyeddl/eddl.py", line 2889, in import_net_from_onnx_file
    return _eddl.import_net_from_onnx_file(path, mem, log_level)
RuntimeError: RuntimeError: LDense
```

**Comment by simleo** [comment] 2022-02-14 11:20
I was able to reproduce the issue. This is not Python-specific though. If you run the following C++ program you get the same error:

```cpp
#include "eddl/apis/eddl.h"
#include "eddl/serialization/onnx/eddl_onnx.h"
#include <iostream>

using namespace eddl;

Tensor *onehot(Tensor *in, int vocs)
{
  int n=in->shape[0];
  int l=in->shape[1];
  int c=0;

  Tensor *out=new Tensor({n,l,vocs});
  out->fill_(0.0);

  int p=0;
  for(int i=0;i<n*l;i++,p+=vocs) {
    int w=in->ptr[i];
    if (w==0) c++;
    out->ptr[p+w]=1.0;
  }

  cout<<"padding="<<(100.0*c)/(n*l)<<"%"<<endl;
  return out;
}

int main() {
    int bs = 20;
    int visual_dim = 3;
    int semantic_dim = 3;
    int vs = 3;
    int emb_size = 200;
    int n_tokens = 3;
    
    Tensor* visual_x = Tensor::randn({bs, visual_dim});
    Tensor* semantic_x = Tensor::randn({bs, semantic_dim});
    
    Tensor* text = Tensor::randn({bs, n_tokens, vs});
    text = onehot(text, vs);
    
    // INPUT: visual features
    layer cnn_top_in = Input({visual_dim}, "in_visual_features");
    layer visual_features = RandomUniform(Dense(cnn_top_in, cnn_top_in->output->shape[1], "visual_features"));
    layer alpha_v = Softmax(Dense(Tanh(visual_features), visual_features->output->shape[1]), -1, "alpha_v");  // missing sentence component
    layer v_att = Mult(alpha_v, visual_features);
    
    // INPUT: semantic features
    layer cnn_out_in = Input({semantic_dim}, "in_semantic_features");
    layer semantic_features = RandomUniform(Embedding(ReduceArgMax(cnn_out_in, {0}), cnn_out_in->output->shape[1], 1, emb_size, "semantic_features"), -0.05, 0.05);
    layer alpha_s = Softmax(Dense(Tanh(semantic_features), emb_size), -1, "alpha_s");  // missing sentence component cnn_out->output->shape[1]
    layer s_att = Mult(alpha_s, semantic_features);
    
    // co-attention (not exactly, just a reference to the full model)
    layer features = Concat({v_att, s_att}, 0, "co_att_in");
    layer context = Dense(features, emb_size, "co_attention");
    
    // lstm
    layer word_in = Input({vs});
    layer to_lstm = ReduceArgMax(word_in, {0});
    to_lstm = RandomUniform(Embedding(to_lstm, vs, 1, emb_size, true, "word_embeddings"), -0.05, +0.05);
    to_lstm = Concat({to_lstm, context});
    layer lstm = LSTM(to_lstm, emb_size, true, false, "lstm");
    setDecoder(word_in);
    
    layer out_lstm = Softmax(Dense(lstm, vs, "top_dense"), -1, "rnn_out");
    
    // model
    model rnn = Model({cnn_top_in, cnn_out_in}, {out_lstm});
    build(rnn, adam(0.001), {"softmax_cross_entropy"}, {"accuracy"}, CS_CPU(-1, "full_mem"));
    summary(rnn);
    
    fit(rnn, {visual_x, semantic_x}, {text}, bs, 1);
    
    save_net_to_onnx_file(rnn, "rnn.onnx");
    // XXX
    rnn = import_net_from_onnx_file("rnn.onnx");
}
```

It looks like the input to one of the `Dense` layers gets somehow corrupted during the serialization / deserialization round trip. Perhaps the EDDL team can help.

**Comment by simleo** [comment] 2022-02-17 08:56
There's a fix for this in the EDDL develop branch, which should be picked up in the next release, see https://github.com/deephealthproject/eddl/issues/328#issuecomment-1040492780

**Closed by simleo** 2022-02-17 08:56 UTC
